"""empty message

Revision ID: 0de5ec0cb554
Revises: fbd733456a31
Create Date: 2023-11-29 05:43:28.359185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de5ec0cb554'
down_revision = 'fbd733456a31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movieId', sa.Integer(), nullable=True))
        batch_op.alter_column('timestamp',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_column('movieid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movieid', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('timestamp',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('movieId')

    # ### end Alembic commands ###
