"""empty message

Revision ID: 76dee82a10de
Revises: 237d59044303
Create Date: 2023-11-29 11:51:10.247709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76dee82a10de'
down_revision = '237d59044303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movieId', sa.Integer(), nullable=False))
        batch_op.drop_column('movieid')

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movieid', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('movieId')

    # ### end Alembic commands ###
