"""empty message

Revision ID: a1cf61477adf
Revises: 8f06c307dd10
Create Date: 2023-11-29 03:41:09.763219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1cf61477adf'
down_revision = '8f06c307dd10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movieId', sa.Integer(), nullable=True))
        batch_op.alter_column('userid',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_column('movieid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movieid', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('timestamp',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('userid',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('movieId')

    # ### end Alembic commands ###
