"""empty message

Revision ID: fbd733456a31
Revises: a1cf61477adf
Create Date: 2023-11-29 04:58:49.496507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd733456a31'
down_revision = 'a1cf61477adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movieId', sa.Integer(), nullable=True))
        batch_op.alter_column('userid',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_column('movieid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movieid', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('timestamp',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('userid',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('movieId')

    # ### end Alembic commands ###
